"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.initalJungle = void 0;
exports.initalJungle = [
    ['Amumu', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Amumu.png'],
    ['Diana', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Diana.png'],
    ['Ekko', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Ekko.png'],
    ['Elise', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Elise.png'],
    ['Evelynn', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Evelynn.png'],
    ['Fiddlesticks', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Fiddlesticks.png'],
    ['Graves', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Graves.png'],
    ['Hecarim', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Hecarim.png'],
    ['Ivern', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Ivern.png'],
    ['Jarvan IV', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/JarvanIV.png'],
    ['Jax', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Jax.png'],
    ['Karthus', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Karthus.png'],
    ['Kayn', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Kayn.png'],
    ["Kha'Zix", 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Khazix.png'],
    ['Kindred', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Kindred.png'],
    ['Lee Sin', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/LeeSin.png'],
    ['Lillia', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Lillia.png'],
    ['Maokai', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Maokai.png'],
    ['Master Yi', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/MasterYi.png'],
    ['Wukong', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/MonkeyKing.png'],
    ['Mordekaiser', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Mordekaiser.png'],
    ['Morgana', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Morgana.png'],
    ['Nidalee', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Nidalee.png'],
    ['Nocturne', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Nocturne.png'],
    ['Nunu & Willump', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Nunu.png'],
    ['Olaf', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Olaf.png'],
    ['Poppy', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Poppy.png'],
    ['Rammus', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Rammus.png'],
    ["Rek'Sai", 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/RekSai.png'],
    ['Rengar', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Rengar.png'],
    ['Sejuani', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Sejuani.png'],
    ['Shaco', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Shaco.png'],
    ['Shyvana', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Shyvana.png'],
    ['Skarner', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Skarner.png'],
    ['Sylas', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Sylas.png'],
    ['Talon', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Talon.png'],
    ['Trundle', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Trundle.png'],
    ['Udyr', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Udyr.png'],
    ['Vi', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Vi.png'],
    ['Volibear', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Volibear.png'],
    ['Warwick', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Warwick.png'],
    ['Xin Zhao', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/XinZhao.png'],
    ['Zac', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Zac.png'],
    ['Zed', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Zed.png'],
];
