export const initialSupport = [
    ['Alistar', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Alistar.png'], 
    ['Amumu', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Amumu.png'],
    ['Annie', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Annie.png'],
    ['Ashe', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Ashe.png'],
    ['Bard', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Bard.png'], 
    ['Blitzcrank', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Blitzcrank.png'], 
    ['Brand', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Brand.png'], 
    ['Braum', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Braum.png'],
    ['Heimerdinger', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Heimerdinger.png'],
    ['Karma', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Karma.png'],
    ['Leona', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Leona.png'],
    ['Lulu', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Lulu.png'], 
    ['Lux', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Lux.png'],
    ['Maokai', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Maokai.png'],
    ['Morgana', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Morgana.png'], 
    ['Nami', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Nami.png'],
    ['Nautilus', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Nautilus.png'],
    ['Pantheon', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Pantheon.png'],
    ['Pyke', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Pyke.png'],
    ['Rakan', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Rakan.png'],
    ['Senna', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Senna.png'], 
    ['Seraphine', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Seraphine.png'],    
    ['Sona', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Sona.png'], 
    ['Soraka', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Soraka.png'], 
    ['Swain', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Swain.png'],
    ['Tahm Kench', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/TahmKench.png'],
    ['Xerath', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Xerath.png'],
    ['Yuumi', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Yuumi.png'],
    ['Zyra', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Zyra.png']
]