export const initalTop = [
    ['Aatrox', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Aatrox.png'],
    ["Cho'Gath", 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Chogath.png'],
    ['Camille', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Camille.png'],
    ['Darius', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Darius.png'],
    ['Dr. Mundo', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/DrMundo.png'],
    ['Fiora', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Fiora.png'],
    ['Gangplank', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Gangplank.png'], 
    ['Garen', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Garen.png'], 
    ['Gnar', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Gnar.png'], 
    ['Gragas', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Gragas.png'],
    ['Illaoi', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Illaoi.png'], 
    ['Irelia', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Irelia.png'],
    ['Jarvan IV', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/JarvanIV.png'], 
    ['Jax', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Jax.png'], 
    ['Jayce', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Jayce.png'],
    ['Kayle', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Kayle.png'],
    ['Kennen', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Kennen.png'],
    ['Kled', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Kled.png'],
    ['Lillia', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Lillia.png'],
    ['Malphite', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Malphite.png'],
    ['Wukong', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/MonkeyKing.png'], 
    ['Mordekaiser', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Mordekaiser.png'],
    ['Nasus', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Nasus.png'],
    ['Olaf', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Olaf.png'],
    ['Ornn', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Ornn.png'],
    ['Pantheon', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Pantheon.png'], 
    ['Poppy', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Poppy.png'],
    ['Quinn', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Quinn.png'],
    ['Renekton', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Renekton.png'], 
    ['Rengar', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Rengar.png'], 
    ['Riven', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Riven.png'], 
    ['Rumble', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Rumble.png'], 
    ['Ryze', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Ryze.png'],
    ['Sett', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Sett.png'],
    ['Shen', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Shen.png'], 
    ['Shyvana', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Shyvana.png'], 
    ['Singed', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Singed.png'], 
    ['Sion', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Sion.png'],
    ['Skarner', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Skarner.png'],
    ['Sylas', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Sylas.png'],
    ['Teemo', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Teemo.png'],
    ['Trundle', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Trundle.png'], 
    ['Tryndamere', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Tryndamere.png'],
    ['Udyr', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Udyr.png'], 
    ['Urgot', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Urgot.png'],
    ['Vayne', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Vayne.png'],
    ['Vladimir', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Vladimir.png'], 
    ['Volibear', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Volibear.png'], 
    ['Warwick', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Warwick.png'],
    ['Yasuo', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Yasuo.png'], 
    ['Yone', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Yone.png'], 
    ['Yorick', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Yorick.png'],
    ['Zac', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Zac.png'],
    
]