export const intialBottom = [
    ['Aphelios', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Aphelios.png'], 
    ['Ashe', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Ashe.png'],
    ['Caitlyn', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Caitlyn.png'],
    ['Corki', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Corki.png'],
    ['Draven', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Draven.png'],
    ['Ezreal', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Ezreal.png'],
    ['Jhin', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Jhin.png'], 
    ['Jinx', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Jinx.png'], 
    ["Kai'Sa", 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Kaisa.png'], 
    ['Kalista', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Kalista.png'],
    ["Kog'Maw", 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/KogMaw.png'],
    ['Lucian', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Lucian.png'],
    ['Miss Fortune', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/MissFortune.png'],
    ['Senna', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Senna.png'],
    ['Sivir', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Sivir.png'],
    ['Tristana', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Tristana.png'],
    ['Twitch', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Twitch.png'],
    ['Varus', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Varus.png'], 
    ['Vayne', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Vayne.png'],
    ['Xayah', 'http://ddragon.leagueoflegends.com/cdn/10.23.1/img/champion/Xayah.png'],
    
]